/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CwCarousel {
        /**
          * if this value is true, a button prev element and a button next element will be shown in the sides of carousel
         */
        "arrows"?: boolean;
        /**
          * if this value is true the elments will be changed automatically in the interval defined
         */
        "autoplay"?: boolean;
        /**
          * set the colors controls carousel
         */
        "colors": string;
        /**
          * set the carousel height
         */
        "height": string;
        /**
          * if this value is true, a section with control indices of elements will be shown at the bottom of the carousel
         */
        "index"?: boolean;
        /**
          * set the interval for altomatically changing the elements
         */
        "time"?: number;
        /**
          * set the carousel width
         */
        "width": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCwCarouselElement extends Components.CwCarousel, HTMLStencilElement {
    }
    var HTMLCwCarouselElement: {
        prototype: HTMLCwCarouselElement;
        new (): HTMLCwCarouselElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cw-carousel": HTMLCwCarouselElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CwCarousel {
        /**
          * if this value is true, a button prev element and a button next element will be shown in the sides of carousel
         */
        "arrows"?: boolean;
        /**
          * if this value is true the elments will be changed automatically in the interval defined
         */
        "autoplay"?: boolean;
        /**
          * set the colors controls carousel
         */
        "colors"?: string;
        /**
          * set the carousel height
         */
        "height"?: string;
        /**
          * if this value is true, a section with control indices of elements will be shown at the bottom of the carousel
         */
        "index"?: boolean;
        /**
          * set the interval for altomatically changing the elements
         */
        "time"?: number;
        /**
          * set the carousel width
         */
        "width"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cw-carousel": CwCarousel;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cw-carousel": LocalJSX.CwCarousel & JSXBase.HTMLAttributes<HTMLCwCarouselElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
